### ISSUE TITLE
Activator behind Proxy

### ISSUE THREAD

**Issue by drewhk** [typesafehub/activator-template-cache#1]
As reported by user:

"On Windows, setting the variables below did not help.

set JAVA_OPTS=-Dhttp.proxyHost=x.y.com -Dhttp.proxyPort=8080
set SBT_OPTS=-Dhttp.proxyHost=x.y.com -Dhttp.proxyPort=8080

Neither parameter affects the sbt-child's java params.

<trace>
Running sbt-child with arguments =
 java
 -Xss1024K
 -Xmx512M
 -XX:PermSize=128M
 -XX:+CMSClassUnloadingEnabled
 -Dactivator.home=//C:/dev/akka-distributed-workers/
 -Dsbt.boot.directory=C:\Documents and Settings\fifi/.sbt
 -Dactivator.sbt-child-port=19161
 -jar C:\dev\akka-distributed-workers\activator-launch-0.2.6.jar
 apply -cp "<classpath stuff>" com.typesafe.sbtchild.SetupSbtChild
 listen
[error] application -

! @6f3k5na80 - Internal server error, for (GET) [/api/templates/49ca4c80-4910-4528-aa34-a658f8c0bede/tutorial/index.html] ->

play.api.Application$$anon$1: Execution exception[[AskTimeoutException: Timed out]]
 at play.api.Application$class.handleError(Application.scala:289)
</trace>"

**Comment by RupeshDeshmukh** [comment]
### There are 2 ways to fix this problem:

**1. Using activatorconfig.txt file**
- Create activatorconfig.txt under C://Users//YOUR USERNAME//.activator directory if does not exists.
- Add below contents to the file:

```
# This are the proxy settings we use for activator
-Dhttp.proxyHost=PUT YOUR PROXY HOST HERE
-Dhttp.proxyPort=PUT YOUR PROXY PORT HERE
# Here we configure the hosts which should not go through the proxy.  You should include your private network, if applicable.
-Dhttp.nonProxyHosts="localhost|127.0.0.1"
# These are commented out, but if you need to use authentication for your proxy, please fill these out.
#-Dhttp.proxyUser=PUT YOUR PROXY USER HERE
#-Dhttp.proxyPassword=PUT YOUR PROXY PASSWORD HERE
```

**2. Changing activator.bat**
- Go the bin directory of activator installation and open activator.bat file in Notepad++
- Add below lines just after "@echo off" line:

```
set HTTP_PROXY=http://<PUT YOUR PROXY HOST HERE>:<PUT YOUR PROXY PORT HERE>
set HTTPS_PROXY=https://<PUT YOUR PROXY HOST HERE>:<PUT YOUR PROXY PORT HERE>
```

**Comment by hantsy** [comment]
I have set `HTTP_PROXY`  then run `activator run`, it seems the `activator` does not read the HTTP proxy settings by default.
